repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^packages/instagram_bot/
    -   id: ruff-format
        files: ^packages/instagram_bot/