version: '3.8'

services:
    postgres:
        container_name: ff-postgres
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile.postgres
        environment:
            DB_USER: myuser
            DB_PASSWORD: mypassword
            DB_NAME: mydatabase
        ports:
            - '5432:5432'

    backend:
        container_name: ff-backend
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile.backend
        environment:
            DB_USER: myuser
            DB_PASSWORD: mypassword
            DB_NAME: mydatabase
            DB_HOST: postgres
            DB_PORT: 5432
        ports:
            - '8080:8080'
        depends_on:
            - postgres
