test_cases = [
    ('Direction Wittenau', ['Wittenau']),
    ('2 blue jacket waiting at Moritzplatz', ['Moritzplatz']),
    ('sind Prinzen Straße ausgestiegen, haben ein paar erwischt', ['Prinzen Straße']),
    (
        'Blaue weste U1/U3 Hallesches Tor nach Warschauer Str',
        ['Hallesches Tor', 'Warschauer Str'],
    ),
    ('BOS leute in Stadtmitte am Gleis', ['Stadtmitte']),
    (
        '5x BOS U6 Unter den Linden nach Alt-Mariendorf UND 2x BOS nach AltTegel',
        ['Unter den Linden', 'Alt-Mariendorf', 'AltTegel'],
    ),
    ('Gleisdreieck, Richtung Warschauer Straße', ['Gleisdreieck', 'Warschauer Straße']),
    ('s1 nach frohnau steigen 2 gelbe westen ein', ['frohnau']),
    ('3x BOS schönleinstr Station', ['schönleinstr']),
    ('Gleisdreieck, on the platform', ['Gleisdreieck']),
    ('3x bacon mit waffe ebenfalls am ostkreuz', ['ostkreuz']),
    ('U8 Moritzplatz Station, 2x BOS blaue Weste', ['Moritzplatz']),
    (
        '2 bvg secu mit hund @ ostkreuz bei gleis 12 gegenüber auf der seite wo nicht der megges is',
        ['ostkreuz'],
    ),
    (
        'U8 Richtung wittenau gerade am rosenthaler ausgestiegen',
        ['wittenau', 'rosenthaler'],
    ),
    ('U1 gleisdreieck richtung kurfürsten', ['gleisdreieck', 'kurfürsten']),
    ('Bernauer ausgestiegen', ['Bernauer']),
    (
        'U6 Paradestr Richtung Kurt Schumacher Platz',
        ['Paradestr', 'Kurt Schumacher Platz'],
    ),
    ('kontrollieren sie ausserhalb?', []),
    ('U6 tempelhof towards alt tegel', ['tempelhof', 'alt tegel']),
    ('U8 voltastr richtung hermannstr', ['voltastr', 'hermannstr']),
    ('4 blauwesten jetzt auf dem Gleis am Kotti', ['Kotti']),
    (
        'Kontrolettis U2 Zoologischer Garten, Richtung Pankow',
        ['Zoologischer Garten', 'Pankow'],
    ),
    ('', []),
    (
        'Controller without vest in S 7 (ahrensfelde) she’s wearing a white jacket. We are at haxkescher markt',
        ['ahrensfelde', 'haxkescher markt'],
    ),
    ('3 U Rosenthaler', ['Rosenthaler']),
    ('1 man, black vest', []),
    (
        'Mehrere blauwesten am schlesischen Tor am gleis, Richtung krumme lanke',
        ['schlesischen Tor', 'krumme lanke'],
    ),
    ('U2 Potsdamer Platz', ['Potsdamer Platz']),
    ('2 blu vest at gorli gave fines u3 und u1', ['gorli']),
    ('Jetzt Görli', ['Görli']),
    ('Jannowitzbrücke u8 Station, 4x bvg gelbweste', ['Jannowitzbrücke']),
    (
        'U8 Richtung wittenau, Jannowitzbrücke, 2x bvg gelbweste',
        ['wittenau', 'Jannowitzbrücke'],
    ),
    ('Ringbahn S 41 in Wedding 4 Männer mit gelber Weste', ['Wedding']),
    ('Jetzt Sonnenallee', ['Sonnenallee']),
    (
        'Drei oder vier Kontrolleure Ring S41 gerade Treptower Park raus',
        ['Treptower Park'],
    ),
    ('', []),
    (
        'Jetzt Bahnsteig Schlesisches Tor Richtung Warschauer',
        ['Schlesisches Tor', 'Warschauer'],
    ),
    ('24h fahradkarte auf automat ostkreuz ringbahnsteig südausgang', ['ostkreuz']),
    ('', []),
    ('', []),
    ('', []),
    ('', []),
    ('', []),
    ('Group in Görlitzebanhof', ['Görlitzebanhof']),
    (
        'U1 Görlitzer Bhf Richtung Warschauer Straße grad ausgestiegen zwei mit blauer Weste',
        ['Görlitzer Bhf', 'Warschauer Straße'],
    ),
    (
        'U2 deutsche oper steigen jetzt Richtung ruhleben ein 3 b.o.s',
        ['deutsche oper', 'ruhleben'],
    ),
    (
        'u1/3 kottbusser tor, zwei blauwesten stehen grad auf der platform und nehmen daten auf',
        ['kottbusser tor'],
    ),
    ('und wieder ausgestiegen prinzenstr!', ['prinzenstr']),
    ('sind grad eingestiegen', []),
    (
        '4 stehen am Bahnhof halleschen Richtung Warschauer',
        ['halleschen', 'Warschauer'],
    ),
    ('U6 alt Tempelhof Richtung alt Mariendorf', ['alt Tempelhof', 'alt Mariendorf']),
    ('U2 Zoo Richtung ruhleben', ['Zoo', 'ruhleben']),
    (
        'Jetz am gorly richtung warschauer.... direkt am gleis ..',
        ['gorly', 'warschauer'],
    ),
    (
        'U6 4-6 Bos paradestraße Richtung alt mariendorf',
        ['paradestraße', 'alt mariendorf'],
    ),
    (
        'Drei bos 2 m gelesen 1 w gelesen u 2 jetzt potsdamer Platz raus',
        ['potsdamer Platz'],
    ),
    ('U8. Aleksandrplaz Directions to wittenau', ['Aleksandrplaz', 'wittenau']),
    ('ostkreuz s5 nach westkreuz.', ['ostkreuz', 'westkreuz']),
    ('Ich meinte u8… bitte entschuldigt (:', []),
    (
        'Tram M13 Borhnholmer Str. , stehen grad an der Halyestelle Ricjtung Westen. 2x männl gelesen, schw jacken, dunkle haare, einer blaue einer schwarze Hose einer hat käppi auf, beide Bart',
        ['Borhnholmer Str'],
    ),
    ('Which station?', []),
    ('Thanks 🙏🏼', []),
    ('kontrolle steigt hackescher aus s5 aus', ['hackescher']),
    ('S 46 Tempelhof vor 10 Minuten', ['Tempelhof']),
    ('Kontrolletis am Gleis 3-4 Alexanderplatz im Zivil gekleidet', ['Alexanderplatz']),
    (
        'S Bellevue, 3 m gelesen, schwarze Kleidung auf dem Bahnsteig Ri.Zoo',
        ['Bellevue', 'Zoo'],
    ),
    ('u5 alexander platz richtung Hönow 2bos westen', ['alexander platz', 'Hönow']),
    ('U7 hermanplatzt gleis', ['hermanplatzt']),
    ('2 BOS Alexanderplatz in der u8', ['Alexanderplatz']),
    ('Steiger gerade bei Sonnenallee ein', ['Sonnenallee']),
    ('Ringbahn S42', []),
    ('Mit Weste oder zivi?', []),
    ('hallesches tor u6', ['hallesches tor']),
    ('2 Kontrolleure männlich gelesen s 42 Frankfurter Allee', ['Frankfurter Allee']),
    ('black jacket and hat', []),
    (
        'S5 Richtung Lichtenberg. Gerade von ostkreuz... 2 männlich gelesene in dunklen Klamotten',
        ['Lichtenberg', 'ostkreuz'],
    ),
    ('Werden dann wohl wieder weiter', []),
    ('5 bos gerade kotti Richtung warschauer u3 eingestiegen', ['kotti', 'warschauer']),
    ('S42 2x Menschen von BVG am Kontrollieren ', []),
    ('Höhe Südkreuz', ['Südkreuz']),
    ('u7 mehringdam', ['mehringdam']),
    ('u8 Bernauer str nach Hermannstraße', ['Bernauer str', 'Hermannstraße']),
    ('*5 männlich gelesene und eine weiblich gelesene Person', []),
    (
        '2 männlich gelesene Personen S 58 nach Waidmannslust höhe S Treptower Park kontrollieren',
        ['Waidmannslust', 'Treptower Park'],
    ),
    ('U9 wird in beide Richtungen kontrolliert', []),
    ('u8 Richtung Herrmannstr Alex raus', ['Herrmannstr', 'Alex']),
    ('5 blau weste nach gorly u1', ['gorly']),
    (
        '2 man waiting at 240 bus station,  Grunbergerstr. / Warschauerstr',
        ['Grunbergerstr.', 'Warschauerstr'],
    ),
    (
        '4 bos Westen, schönleinstraße am Gleis Richtung wittenau',
        ['schönleinstraße', 'wittenau'],
    ),
    ('4 x b.o.s Alexanderplatz u2', ['Alexanderplatz']),
    ('U8 weinmeisterstr', ['weinmeisterstr']),
    ('S7 Alexander platz direction Ostkreuz', ['Alexander platz', 'Ostkreuz']),
    ('S41 landsberger', ['landsberger']),
    ('2 männlich gelesen eine weiblich', []),
    ('S25 Richtung Teltow Stadt, gerade Humboldhain', ['Teltow Stadt', 'Humboldhain']),
    ('U7 Richtung Spandau Höhe Südstern letzter Wagen', ['Spandau', 'Südstern']),
    ('3 leute', []),
    (
        'S7 Richtung ahrensfelde letzter Wagen, jetzt zwischen nöldnerplatz und lichtenberg',
        ['ahrensfelde', 'nöldnerplatz', 'lichtenberg'],
    ),
    ('S41 gerade Höhe Heidelberger Platz', ['Heidelberger Platz']),
    ('U5 richtung hauptbahnhof, rotes rathaus', ['hauptbahnhof', 'rotes rathaus']),
    ('Beide in Sportjacken..blau und weiß grau', []),
    ('M41 Bus richtung hbf gleich Willy Brandt Haus', ['hbf', 'Willy Brandt']),
    ('Waiting S7 to come', []),
    ('', []),
    ('Bleiben drin', []),
    (
        '2 bos U8 hermannplatz, stehen Richtung Hermastraße',
        ['hermannplatz', 'Hermastraße'],
    ),
    ('Richtung Osloer', ['Osloer']),
    ('Sind schönlein raus', ['schönlein']),
    ('bos westen am alexanderplatz u2', ['alexanderplatz']),
    ('10:57 uhr, weitergeleitet:', []),
    ('', []),
    ('U6 Wedding', ['Wedding']),
    ('Richtung Norden', []),
    (
        'Wittenbergplatz u2 Richtung Ruhleben 3 in bvg Ausrüstung',
        ['Wittenbergplatz', 'Ruhleben'],
    ),
    (
        'U8 richtung hermannstraße gleich schönleinstrasse',
        ['hermannstraße', 'schönleinstrasse'],
    ),
    ('2x  Turmstraße auf dem Gleis', ['Turmstraße']),
    (
        'U6 Leopoldplatz Richtung Kurt-Schumacher-Platz',
        ['Leopoldplatz', 'Kurt-Schumacher-Platz'],
    ),
    ('S7 Tiergarten gerade Richtung Ahrensfelde', ['Tiergarten', 'Ahrensfelde']),
    ('U 9 Birkenstraße 5 blauwesten', ['Birkenstraße']),
    (
        'Kontrolle. 4 männlich gelesene Menschen Innsbrucker Platz s 42‘',
        ['Innsbrucker Platz'],
    ),
    ('U8 bernauerstr 3 blaue westen', ['bernauerstr']),
    (
        'Zwei männlich gelesen Tiergarten eingestiegen, Steigen Hauptbahnhof aus, sind beide schwarz gekleidet.',
        ['Tiergarten', 'Hauptbahnhof'],
    ),
    ('U8 moritzplatz bos Jacken gerade auf der Platform', ['moritzplatz']),
    ('U9 Leopoldplatz', ['Leopoldplatz']),
    ('S Bahn nach Spandau grade westkreutz', ['Spandau', 'westkreutz']),
    ('S26 Richtung Teltow Nordbahnhof', ['Teltow']),
    ('2 blue vest', []),
    (
        'U8 kottbusser tor in der mitte des bahnsteiges stehen 6 personen 3 blaue Western 3 gelbe ',
        ['kottbusser tor'],
    ),
    ('Kontrollieren allen anscheinend nach beim rausgehen', []),
    ('Nauener Platz.', ['Nauener Platz.']),
    ('U9 richtung Rathaus Steglitz.', ['Rathaus Steglitz']),
    ('3-4 Menschen mit Blauwesten.', []),
    (
        '4 green vests just got of at ostbahnhof. S3 towards erkner',
        ['ostbahnhof', 'erkner'],
    ),
    ('U5 nochmal andere Kontrolettis. Gerade Brandenburger Tor', ['Brandenburger Tor']),
    ('Sind ausgestiegen', []),
    ('U6 Naturkundemuseum aus', ['Naturkundemuseum']),
    ('Richtung Hauptbahnhof', ['Hauptbahnhof']),
    (
        'S8 to Birkenwerder from Bornholmer Straße women with blue jacket grey scarf',
        ['Birkenwerder', 'Bornholmer Straße'],
    ),
    (
        '2 männlich gelesene, 1 weiblich gelesene Person steigen gerade Schönhause Allee in die S41',
        ['Schönhause Allee'],
    ),
    ('U2 Bülowstr. 2m 1w Kontro', ['Bülowstr.']),
    ('U8 nach Hermannstraße Bernauer Straße', ['Hermannstraße', 'Bernauer Straße']),
    (
        'Jemand n Tipp für BVG app? Neues Handy hab mich im acc eingeloggt und die Monatskarte ist verschwunden.',
        [],
    ),
    (
        'S41 Innsbrucker ausgestiegen , eine Person mit mütze und weissem Jogger',
        ['Innsbrucker'],
    ),
    (
        'Jetzt gleich. Alt Reinickendorf. Haben sehr schlechte Laune.',
        ['Alt Reinickendorf'],
    ),
    (
        's7 raoul wallenberg str richtung potsdam hbf',
        ['aoul wallenberg str', 'potsdam hbf'],
    ),
    (
        'Sind weiterhin in der S25 hinten. Gleich Karl-Boenhöffer Nervenklinik',
        ['Karl-Boenhöffer Nervenklinik'],
    ),
    ('Sind wieder rein fahren weiter Richtung Süden', []),
    (
        'Drei Typen auf dem Gleis S Lichtenberg. Einer mit brauner Lederjacke',
        ['Lichtenberg'],
    ),
    ('09:34 uhr, weitergeleitet:', []),
    ('', []),
    ('U5 Rotes Rathaus', ['Rotes Rathaus']),
    ('Richtung Hönow', ['Hönow']),
    ('mindestens 1 Konti, blaue Weste', []),
    ('Ringbahn Schönhauser Allee ausgestiegen', ['Schönhauser Allee']),
    ('Hellesdorf ausgestiegen 2m gelesene', ['Hellesdorf']),
    ('M2 richtung Alex', ['Alex']),
    (
        'S25 Richtung henningsdorf 2 männlich gelesene Kontros sind Höhe eichborndamm',
        ['henningsdorf', 'eichborndamm'],
    ),
    (
        'S26 Richtung Teltow Stadt, Priesterweg.... 2 Frauen 1 man, normal gekleidet, schwarz',
        ['Teltow Stadt', 'Priesterweg'],
    ),
    ('S9 Friedrichstraße auf dem Gleis 3 grüne Weste', ['Friedrichstraße']),
    ('Na dann machen wir denn mal  richtig schlechte Laune', []),
    (
        'In S25 nach Hennigsdorf drei Kontis in Zivil gleich Schönhoz',
        ['Hennigsdorf', 'Schönhoz'],
    ),
    (
        'U9 richtung Steglitz 4 BOS, grade Hansaplatz eingestiegen, jetzt Zoo raus',
        ['Steglitz', 'Hansaplatz', 'Zoo'],
    ),
    ('u2 mohrenstr. 3 people', ['mohrenstr']),
    (
        'S85 nach waidmannslust  gleich Storkower Str.',
        ['waidmannslust', 'Storkower Str'],
    ),
    ('01 person yellow jacket on M12 around Dirckenstr', ['Dirckenstr']),
    (
        'U7 Yorkstr haben 3 Richtung Spandau kontrolliert und steigen aus.',
        ['Yorkstr', 'Spandau'],
    ),
    ('sind alex raus und gehen jetzt vermutlich die ganze bahn durch ', ['alex']),
    ('sind zu 4.', []),
    (
        'grüne westen in die s5 richtung strausberg nord eingestiegen',
        ['strausberg nord'],
    ),
    ('nächste station hackescher markt', ['hackescher markt']),
    ('Kontrolettis s Köpenick', ['Köpenick']),
    ('s charlottenburg towards east (got off s3 just now)', ['charlottenburg ']),
    ('s3 nach erkner', ['erkner']),
    ('zwischen heerstr und messe süd', ['heerstr', 'messe süd']),
    (
        'U9 Leopoldplatz direct. Rathaus Steglitz 3 blue vests at station',
        ['Leopoldplatz', 'Rathaus Steglitz'],
    ),
    ('U7 hermannplatz  Richtung spandau', ['hermannplatz', 'spandau']),
    (
        '2 kontrollöre Goslarer Platz warten auf den m27 Richtung Pankow',
        ['Goslarer Platz', 'Pankow'],
    ),
    ('Wegelagerei S7 Marzahn ', ['Marzahn ']),
    ("2 Typen (wie kann man nur so\'n job machen?)", []),
    (
        'In der S45 nach Flughafen BER, gleich in Waßmannsdorf. Ein Mann in zivil.',
        ['Flughafen BER', 'Waßmannsdorf'],
    ),
    ('3 Kontrolleure s9 Richtung BER', ['BER']),
    ('Nächster halt Schönefeld', ['Schönefeld']),
    ('Ist raus.', []),
    (
        '@Michaelh3alth vertickt Drogen und hat mich durch Account X in seine Drogengruppe geholt ohne Zustimmung.',
        [],
    ),
    ('A lot of popo in the u8 👮', []),
    (
        'platz der luftbrücke richtung Kurt Schumacher Platz',
        ['platz der luftbrücke', 'Kurt Schumacher Platz'],
    ),
    ('Just went out of u8', []),
    ('U8', []),
    ('Blau vest am Alex jetzt', ['Alex']),
    ('Next is janowitzbruche', ['janowitzbruche']),
    ('2 controllers u8', []),
    ('Left Heinrich heine', ['Heinrich heine']),
    (
        'Schlesisches Tor, U1 Ri Warschauer Str. eingestiegen ',
        ['Schlesisches Tor', 'Warschauer Str.'],
    ),
    ('2 Kötter Blauwesten männlich gelesen', []),
    ('Warum nicht?', []),
    ('Bitte zur @Diskussionsgruppe', []),
    ('Direction south', []),
    ('Stadtmitte U6', ['Stadtmitte']),
    ('stadmitte u6', ['stadmitte']),
    ('2 blue vests Kotti u8', ['Kotti']),
    ('Götlitzer bahnhof blaue weste raus', ['Götlitzer bahnhof']),
]
