import { i18n } from '@/lib/i18n';

export const NAMESPACE = 'privacyPolicy';

i18n.addResourceBundle('en', NAMESPACE, {
  title: 'Privacy Policy',
  sections: {
    preamble: {
      title: '1. Preamble',
      content:
        'This Privacy Policy informs you about the nature, scope, and purpose of the processing of personal data in the mobile application "Freifahren" (hereinafter referred to as "App"). The App allows users to report incidents in public transport and share this information with other users. Additionally, reports are generated by the non-deterministic and anonymized evaluation of messages from the Freifahren_BE Telegram group.',
    },
    responsible: {
      title: '2. Responsible Party',
      content:
        'The controller responsible for data processing within this App is FreiFahren e.V. - Johan Trieloff (Chairman), c/o Online-Impressum #7591, Europaring 90, 53757 Sankt Augustin, reachable via contact@freifahren.org. Authorized board members: Johan Trieloff (johan@freifahren.org), Moritz Clerc (moritz@freifahren.org), David Brandes (david@freifahren.org).',
    },
    legalBasis: {
      title: '3. Legal Basis for Data Processing',
      content:
        'The processing of personal data in our App is based on the following legal grounds in accordance with the General Data Protection Regulation (GDPR):',
      consent:
        'Consent (Art. 6(1)(a) GDPR): Users of our App provide their explicit consent for the processing of their personal data for specific purposes. This consent can be withdrawn at any time with effect for the future, whereby the withdrawal does not affect the lawfulness of the processing carried out up to that point.',
      legitimateInterest:
        'Legitimate interests (Art. 6(1)(f) GDPR): Processing is necessary to protect the legitimate interests of the controller or a third party, provided these interests are not overridden by the interests or fundamental rights and freedoms of the data subject. Our legitimate interests include in particular ensuring the functionality and security of the service, improving the App, and preventing abuse.',
    },
    dataUsage: {
      title: '4. Data Collection and Usage',
      content: 'The App collects data in three different contexts:',
      reportFormTitle: 'When creating a report:',
      dataPoints: [
        'Line (optional)',
        'Station',
        'Direction (optional)',
        'Report timestamp',
        "User's IP address",
      ],
      reportPurpose:
        'The reported data is temporarily made available to other users of the App to provide them with information about the current situation in public transport. Additionally, the reports are forwarded to the Freifahren_BE Telegram group. This data transmission serves the purpose of sharing and informing the community about incidents. For information regarding the transfer to Telegram, please refer to Section 11; for information on international data transfers, please refer to Section 14.',
      ipAddressInfo:
        'FreiFahren itself does not store IP addresses. To protect against spam and abuse, Cloudflare as an upstream infrastructure provider processes IP addresses briefly. In doing so, Cloudflare acts predominantly as a processor pursuant to Art. 28 GDPR on our instruction (see Section 15); for the prevention of attacks and abuse (security telemetry), Cloudflare additionally acts as an independent controller. This processing is based on legitimate interests pursuant to Art. 6(1)(f) GDPR (ensuring the security and functionality of the service). For information regarding the associated transfer to a third country, please refer to Section 14.',
      paymentFormTitle: 'When making a voluntary contribution via Stripe:',
      paymentDataPoints: [
        'Name (if provided)',
        'Email address (if provided)',
        'Transaction data (amount, date, payment reference)',
      ],
      paymentPurpose:
        "Payment processing is handled via a Stripe-hosted payment link. The contracting party is Stripe Payments Europe, Ltd. (1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Ireland); within its corporate group, transfers to its US parent company Stripe, Inc. may occur (see Section 14). Payment data is entered directly on the page operated by Stripe; card data is processed exclusively by Stripe and is not transmitted to us. As part of the process, Stripe transmits transaction data to FreiFahren e.V., which may include the payer's name and email address depending on the information provided. Processing is based on Art. 6(1)(b) GDPR (handling of the voluntary contribution). For information on the related international data transfer, please refer to Section 14.",
    },
    anonymity: {
      title: '5. Anonymity',
      content:
        'No permanently personal data of users is stored. The IP address is considered personal data, but is not stored persistently by FreiFahren and is not reconstructable. For reports originating from the publicly accessible FreiFahren_BE Telegram group, an indirect link to the respective Telegram account could theoretically be established through correlation of timestamps. We recommend users with a heightened privacy interest to submit reports directly via the app.',
    },
    storageAndAccess: {
      title: '6. Storage and Access',
      content:
        "Collected data is stored on FreiFahren e.V.'s own servers, hosted by Hetzner Online GmbH in Germany. Access is strictly limited to authorized association members.",
    },
    userRights: {
      title: '7. User Rights',
      intro:
        'You have the following rights vis-à-vis FreiFahren e.V. with regard to the personal data concerning you:',
      rightsList: {
        access:
          'Right of access (Art. 15 GDPR): You may request information about the personal data we process about you.',
        rectification:
          'Right to rectification (Art. 16 GDPR): You may request the rectification of inaccurate data or the completion of incomplete data.',
        erasure:
          'Right to erasure (Art. 17 GDPR): You may request the deletion of your personal data, provided the legal requirements are met.',
        restriction:
          'Right to restriction of processing (Art. 18 GDPR): Under certain conditions, you may request that the processing of your data be restricted.',
        portability:
          'Right to data portability (Art. 20 GDPR): You may request to receive the data concerning you in a structured, commonly used, and machine-readable format.',
        objection:
          'Right to object (Art. 21 GDPR): You may object at any time, on grounds relating to your particular situation, to the processing of your data that is based on legitimate interests (Art. 6(1)(f) GDPR).',
        withdrawConsent:
          'Right to withdraw consent (Art. 7(3) GDPR): Where processing is based on your consent, you may withdraw it at any time with effect for the future. The lawfulness of the processing carried out up to the point of withdrawal remains unaffected.',
        complaint:
          'Right to lodge a complaint with a supervisory authority (Art. 77 GDPR): Without prejudice to any other remedy, you have the right to lodge a complaint with a data protection supervisory authority. The competent authority for FreiFahren e.V. is in particular the Berlin Commissioner for Data Protection and Freedom of Information (Berliner Beauftragte für Datenschutz und Informationsfreiheit), Alt-Moabit 59-61, 10555 Berlin, Germany (mailbox@datenschutz-berlin.de).',
      },
      contact:
        'To exercise your rights, you may contact us informally by email at contact@freifahren.org.',
    },
    consent: {
      title: '8. Consent to the Privacy Policy',
      content:
        'No separate consent is required for general use of the App or for submitting reports. No separate consent is required for voluntary contributions via Stripe either; the transaction data is processed in order to handle the contribution (Art. 6(1)(b) GDPR).',
    },
    dataProtectionOfficer: {
      title: '9. Data Protection Contact',
      content:
        'For questions regarding data protection, please contact us via contact@freifahren.org.',
    },
    policyChanges: {
      title: '10. Changes to the Privacy Policy',
      content:
        'We reserve the right to change this Privacy Policy to reflect changes in legal conditions, the App, or data processing. Users are encouraged to regularly review the content of the Privacy Policy.',
    },
    telegramMessages: {
      title: '11. Processing of Telegram Messages',
      content:
        "Messages from the Freifahren_BE group are evaluated by the Freifahren Telegram Bot with the consent of the administrators. Messages are not stored and are only used for real-time evaluation. Only the non-deterministically extracted information (direction, line, and station) from the messages is stored. The timestamp is rounded to ensure anonymity. Even for this anonymized report data, an indirect link to an individual cannot be fully excluded; see Section 5 in this regard. Message evaluation is performed using an AI language model from Mistral AI (Mistral AI SAS, Paris, France). For this, the message text is transmitted for real-time extraction to Mistral AI's API, which is hosted exclusively in the EU. Mistral AI acts as a processor pursuant to Art. 28 GDPR on our instruction; the content is not used to train the models and is retained by Mistral AI only briefly (max. 30 days) for abuse monitoring, if at all. FreiFahren does not store the message texts.",
    },
    errorMonitoring: {
      title: '12. Error Monitoring and Diagnostics',
      description:
        "We use Sentry for error monitoring and crash reporting to maintain and improve our service. The provider is Functional Software, Inc. (Sentry), 45 Fremont Street, 8th Floor, San Francisco, CA 94105, USA. We use Sentry's EU region, so the technical data is processed on servers located within the European Union. When the App encounters an error, we collect anonymized diagnostic information including:",
      dataPoints: {
        os: 'Operating system version',
        appVersion: 'App version',
        device: 'Device type',
        state: 'App state at the time of the error',
      },
      storage:
        'This technical data is stored for a maximum period of 30 days. We explicitly configure Sentry not to collect IP addresses. All data collection is anonymized and used solely for the purpose of identifying and fixing technical issues. Processing is based on legitimate interests pursuant to Art. 6(1)(f) GDPR (ensuring the functionality of the service). As Functional Software, Inc. is headquartered in the United States, a transfer of data to a third country (in particular within its corporate group or in the context of support and maintenance services) cannot be entirely excluded. Please refer to Section 15 for information on the safeguards in place.',
    },
    appStores: {
      title: '13. Distribution via App Stores',
      content:
        'The App is downloaded and installed via the Apple App Store (Apple Distribution International Ltd., Hollyhill Industrial Estate, Hollyhill, Cork, Ireland) and the Google Play Store (Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Ireland). These platforms independently collect data in connection with the download and installation (e.g., Apple ID or Google account, device information, download timestamp, payment information) under their own data protection responsibility. We have no influence on this. The privacy terms of the respective App store operator apply.',
    },
    internationalTransfers: {
      title: '14. International Data Transfers',
      content:
        'In the context of the processing activities described above, data may be transferred to countries outside the European Economic Area (EEA) that do not provide a level of data protection equivalent to that under European law ("third countries"). This concerns in particular the following services:',
      transfers: {
        cloudflare:
          'Cloudflare, Inc. (USA): Used for protection against spam and abuse. The transfer is based on the EU Standard Contractual Clauses (Art. 46(2)(c) GDPR) and - where applicable - on the EU-US Data Privacy Framework (adequacy decision of the EU Commission of 10 July 2023, Art. 45 GDPR).',
        sentry:
          'Functional Software, Inc. / Sentry (USA): Used for error monitoring. Processing primarily takes place in the EU region; any transfers to the United States are based on the EU Standard Contractual Clauses and - where applicable - on the EU-US Data Privacy Framework.',
        telegram:
          "Telegram FZ-LLC (United Arab Emirates): Used for synchronizing reports with the FreiFahren_BE group. No adequacy decision of the EU Commission exists for the UAE. In this context, we exclusively process anonymized report data (line, station, direction, rounded timestamp) without any direct personal identifiers; regarding a possible indirect link to an individual through timestamp correlation, see Section 5. Users who submit reports directly within the Telegram group are advised to consult Telegram's privacy terms.",
        stripe:
          "Stripe Payments Europe, Ltd. (Ireland) / Stripe, Inc. (USA): Used for processing voluntary contributions. The contracting party is Stripe Payments Europe, Ltd., based in Ireland; within its corporate group, transfers to its US parent company Stripe, Inc. may occur. Stripe processes payment data (e.g. card details) under its own data protection responsibility. Any transfers to the US are safeguarded on the basis of the EU Standard Contractual Clauses (Art. 46(2)(c) GDPR) and - where applicable - the EU-US Data Privacy Framework (Stripe is DPF-certified). Stripe's privacy policy is available at https://stripe.com/privacy.",
      },
      rights:
        'You may request a copy of the relevant safeguards (in particular the EU Standard Contractual Clauses) from us at contact@freifahren.org.',
    },
    dataProcessing: {
      title: '15. Data Processing by Service Providers',
      content:
        'Where external service providers are used in the context of data processing, they act as processors within the meaning of Art. 28 GDPR. Data Processing Agreements (Data Processing Addenda) are in place with Sentry (Functional Software, Inc.) and Cloudflare, Inc. Cloudflare, Inc. acts predominantly as a processor; for measures to prevent attacks and abuse, Cloudflare acts as an independent controller. A Data Processing Agreement with Hetzner Online GmbH is in place. A Data Processing Agreement (Data Processing Addendum) with Mistral AI SAS is in place as part of the subscription agreement. The contracting party for payment processing is Stripe Payments Europe, Ltd.; the Data Processing Agreement between the parties forms part of the Stripe Services Agreement. Insofar as Stripe processes payment data for its own purposes (in particular fraud prevention and compliance with regulatory obligations), Stripe acts as an independent controller in that respect.',
    },
  },
});

i18n.addResourceBundle('de', NAMESPACE, {
  title: 'Datenschutzerklärung',
  sections: {
    preamble: {
      title: '1. Präambel',
      content:
        'Diese Datenschutzerklärung informiert Sie über die Art, den Umfang und den Zweck der Verarbeitung personenbezogener Daten in der mobilen Anwendung "Freifahren" (im Folgenden "App"). Die App ermöglicht es Nutzern, Vorfälle im öffentlichen Nahverkehr zu melden und diese Informationen anderen Nutzern zur Verfügung zu stellen. Zudem werden Meldungen durch das nicht deterministische und anonymisierte Auswerten der Nachrichten der Freifahren_BE Telegram-Gruppe generiert.',
    },
    responsible: {
      title: '2. Verantwortliche Stelle',
      content:
        'Verantwortlich für die Datenverarbeitung im Rahmen dieser App ist FreiFahren e.V. - Johan Trieloff (Vorstandsvorsitzender), c/o Online-Impressum #7591, Europaring 90, 53757 Sankt Augustin, erreichbar unter contact@freifahren.org. Vertretungsberechtigter Vorstand: Johan Trieloff (johan@freifahren.org), Moritz Clerc (moritz@freifahren.org), David Brandes (david@freifahren.org).',
    },
    legalBasis: {
      title: '3. Rechtsgrundlagen der Datenverarbeitung',
      content:
        'Die Verarbeitung personenbezogener Daten in unserer App erfolgt auf Basis der folgenden Rechtsgrundlagen gemäß der Datenschutz-Grundverordnung (DSGVO):',
      consent:
        'Einwilligung (Art. 6 Abs. 1 lit. a DSGVO): Die Nutzer unserer App geben ihre ausdrückliche Einwilligung zur Verarbeitung ihrer personenbezogenen Daten für spezifische Zwecke. Diese Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden, wobei der Widerruf die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung nicht berührt.',
      legitimateInterest:
        'Berechtigte Interessen (Art. 6 Abs. 1 lit. f DSGVO): Die Verarbeitung ist zur Wahrung der berechtigten Interessen des Verantwortlichen oder eines Dritten erforderlich, sofern nicht die Interessen oder Grundrechte und Grundfreiheiten der betroffenen Person überwiegen. Die berechtigten Interessen umfassen insbesondere die Sicherstellung der Funktionsfähigkeit und Sicherheit des Dienstes, die Verbesserung der App sowie die Missbrauchsprävention.',
    },
    dataUsage: {
      title: '4. Erhebung und Nutzung von Daten',
      content: 'Die App erhebt Daten in drei verschiedenen Kontexten:',
      reportFormTitle: 'Bei der Erstellung einer Meldung:',
      dataPoints: [
        'Linie (optional)',
        'Station',
        'Richtung (optional)',
        'Uhrzeit der Meldung',
        'IP-Adresse des Nutzers',
      ],
      reportPurpose:
        'Die gemeldeten Daten werden anderen Nutzern der App temporär zur Verfügung gestellt, um ihnen die Möglichkeit zu geben, sich über die aktuelle Situation in den öffentlichen Verkehrsmitteln zu informieren. Des Weiteren werden die Meldungen in die Freifahren_BE Telegram-Gruppe weitergeleitet. Diese Datenübermittlung dient dem Austausch und der Information über Vorfälle innerhalb der Community. Hinweise zur Übermittlung an Telegram finden Sie in Abschnitt 11 sowie zu internationalen Datenübermittlungen in Abschnitt 14.',
      ipAddressInfo:
        'FreiFahren selbst speichert keine IP-Adressen. Zur Abwehr von Spam und Missbrauch verarbeitet Cloudflare als vorgelagerter Infrastruktur-Dienstleister IP-Adressen kurzfristig. Cloudflare wird dabei überwiegend als Auftragsverarbeiter nach Art. 28 DSGVO auf unsere Weisung tätig (siehe Abschnitt 15); für die Abwehr von Angriffen und Missbrauch (Sicherheitstelemetrie) handelt Cloudflare zudem als eigenständig Verantwortlicher. Diese Verarbeitung erfolgt auf Grundlage berechtigter Interessen gemäß Art. 6 Abs. 1 lit. f DSGVO (Sicherstellung der Sicherheit und Funktionsfähigkeit des Dienstes). Hinweise zum damit verbundenen Drittlandtransfer finden Sie in Abschnitt 14.',
      paymentFormTitle: 'Bei einer freiwilligen Beitragszahlung über Stripe:',
      paymentDataPoints: [
        'Name (sofern angegeben)',
        'E-Mail-Adresse (sofern angegeben)',
        'Transaktionsdaten (Betrag, Datum, Zahlungsreferenz)',
      ],
      paymentPurpose:
        'Die Zahlungsabwicklung erfolgt über einen von Stripe gehosteten Payment-Link. Vertragspartner ist die Stripe Payments Europe, Ltd. (1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland); im Konzernverbund kann es zu Übermittlungen an die US-Muttergesellschaft Stripe, Inc. kommen (siehe Abschnitt 14). Die Zahlungsdaten werden direkt auf der von Stripe betriebenen Seite eingegeben; Kartendaten werden ausschließlich von Stripe verarbeitet und nicht an uns übermittelt. Im Rahmen der Abwicklung übermittelt Stripe an FreiFahren e.V. Transaktionsdaten, die je nach Eingabe den Namen und die E-Mail-Adresse des Zahlenden enthalten können. Die Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO (Abwicklung des freiwilligen Beitrags). Hinweise zum damit verbundenen Drittlandtransfer finden Sie in Abschnitt 14.',
    },
    anonymity: {
      title: '5. Anonymität',
      content:
        'Es werden keine dauerhaft personenbezogenen Daten der Nutzer gespeichert. IP-Adressen gelten als personenbezogene Daten, werden durch FreiFahren jedoch nicht persistent gespeichert und sind nicht rekonstruierbar. Bei Meldungen, die ihren Ursprung in der öffentlich zugänglichen FreiFahren_BE-Telegram-Gruppe haben, kann theoretisch durch Korrelation der Zeitstempel ein indirekter Bezug zum jeweiligen Telegram-Account hergestellt werden. Wir empfehlen Nutzern, die ein erhöhtes Schutzinteresse haben, Meldungen direkt über die App zu senden.',
    },
    storageAndAccess: {
      title: '6. Speicherung und Zugriff',
      content:
        'Die erhobenen Daten werden auf eigenen Servern des FreiFahren e.V. gespeichert, die bei der Hetzner Online GmbH in Deutschland gehostet sind. Der Zugriff ist strikt auf autorisierte Vereinsmitglieder beschränkt.',
    },
    userRights: {
      title: '7. Rechte der Nutzer',
      intro:
        'Sie haben gegenüber FreiFahren e.V. folgende Rechte hinsichtlich der Sie betreffenden personenbezogenen Daten:',
      rightsList: {
        access:
          'Recht auf Auskunft (Art. 15 DSGVO): Sie können Auskunft darüber verlangen, welche personenbezogenen Daten wir über Sie verarbeiten.',
        rectification:
          'Recht auf Berichtigung (Art. 16 DSGVO): Sie können die Berichtigung unrichtiger oder die Vervollständigung unvollständiger Daten verlangen.',
        erasure:
          'Recht auf Löschung (Art. 17 DSGVO): Sie können die Löschung Ihrer personenbezogenen Daten verlangen, sofern die gesetzlichen Voraussetzungen vorliegen.',
        restriction:
          'Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO): Sie können unter bestimmten Voraussetzungen die Einschränkung der Verarbeitung Ihrer Daten verlangen.',
        portability:
          'Recht auf Datenübertragbarkeit (Art. 20 DSGVO): Sie können verlangen, die Sie betreffenden Daten in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten.',
        objection:
          'Recht auf Widerspruch (Art. 21 DSGVO): Sie können der Verarbeitung Ihrer Daten, die auf Grundlage berechtigter Interessen (Art. 6 Abs. 1 lit. f DSGVO) erfolgt, jederzeit aus Gründen, die sich aus Ihrer besonderen Situation ergeben, widersprechen.',
        withdrawConsent:
          'Recht auf Widerruf der Einwilligung (Art. 7 Abs. 3 DSGVO): Sofern die Verarbeitung auf Ihrer Einwilligung beruht, können Sie diese jederzeit mit Wirkung für die Zukunft widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung bleibt unberührt.',
        complaint:
          'Recht auf Beschwerde bei einer Aufsichtsbehörde (Art. 77 DSGVO): Unbeschadet anderweitiger Rechtsbehelfe steht Ihnen das Recht zu, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Zuständig für FreiFahren e.V. ist insbesondere die Berliner Beauftragte für Datenschutz und Informationsfreiheit, Alt-Moabit 59-61, 10555 Berlin (mailbox@datenschutz-berlin.de).',
      },
      contact:
        'Anfragen zur Wahrnehmung Ihrer Rechte können Sie formlos per E-Mail an contact@freifahren.org richten.',
    },
    consent: {
      title: '8. Einwilligung zur Datenschutzerklärung',
      content:
        'Für die Nutzung der App sowie für das Absenden von Meldungen ist keine gesonderte Einwilligung erforderlich. Auch für die freiwillige Beitragszahlung über Stripe ist keine gesonderte Einwilligung erforderlich; die Verarbeitung der Transaktionsdaten erfolgt zur Abwicklung des Beitrags (Art. 6 Abs. 1 lit. b DSGVO).',
    },
    dataProtectionOfficer: {
      title: '9. Datenschutzkontakt',
      content: 'Für Fragen zum Datenschutz erreichen Sie uns unter contact@freifahren.org.',
    },
    policyChanges: {
      title: '10. Änderungen an der Datenschutzerklärung',
      content:
        'Wir behalten uns vor, diese Datenschutzerklärung zu ändern, um sie an geänderte Rechtslagen oder Änderungen der App sowie der Datenverarbeitung anzupassen. Nutzer werden gebeten, sich regelmäßig über den Inhalt der Datenschutzerklärung zu informieren.',
    },
    telegramMessages: {
      title: '11. Verarbeitung von Telegram-Nachrichten',
      content:
        'Durch den Freifahren Telegram Bot werden Nachrichten aus der Freifahren_BE-Gruppe mit Zustimmung der Administratoren ausgewertet. Die Nachrichten werden nicht gespeichert und nur für die Echtzeit-Auswertung verwendet. Es werden lediglich die nicht deterministisch extrahierten Informationen (Richtung, Linie und Station) aus den Nachrichten gespeichert. Die Uhrzeit wird abgerundet, um die Anonymität zu gewährleisten. Auch bei diesen anonymisierten Meldedaten kann ein indirekter Personenbezug nicht vollständig ausgeschlossen werden; siehe hierzu Abschnitt 5. Die Auswertung der Nachrichten erfolgt mithilfe eines KI-gestützten Sprachmodells des Anbieters Mistral AI (Mistral AI SAS, Paris, Frankreich). Hierzu wird der Nachrichtentext zur Echtzeit-Extraktion an die ausschließlich in der EU gehostete API von Mistral AI übermittelt. Mistral AI wird dabei als Auftragsverarbeiter nach Art. 28 DSGVO auf unsere Weisung tätig; die Inhalte werden nicht zum Training der Modelle verwendet und von Mistral AI allenfalls kurzfristig (max. 30 Tage) zur Missbrauchserkennung vorgehalten. Eine Speicherung der Nachrichtentexte durch FreiFahren erfolgt nicht.',
    },
    errorMonitoring: {
      title: '12. Fehlererkennung und Diagnose',
      description:
        'Wir verwenden Sentry zur Fehlererkennung und Absturzberichterstattung, um unseren Service zu warten und zu verbessern. Anbieter ist die Functional Software, Inc. (Sentry), 45 Fremont Street, 8th Floor, San Francisco, CA 94105, USA. Wir nutzen die EU-Region von Sentry, sodass die technischen Daten auf Servern innerhalb der Europäischen Union verarbeitet werden. Wenn die App einen Fehler feststellt, sammeln wir anonymisierte Diagnoseinformationen, einschließlich:',
      dataPoints: {
        os: 'Betriebssystemversion',
        appVersion: 'App-Version',
        device: 'Gerätetyp',
        state: 'App-Status zum Zeitpunkt des Fehlers',
      },
      storage:
        'Diese technischen Daten werden für maximal 30 Tage gespeichert. Wir konfigurieren Sentry ausdrücklich so, dass keine IP-Adressen erfasst werden. Alle Datenerfassung erfolgt anonymisiert und dient ausschließlich der Identifizierung und Behebung technischer Probleme. Die Verarbeitung erfolgt auf Grundlage berechtigter Interessen gemäß Art. 6 Abs. 1 lit. f DSGVO (Sicherstellung der Funktionsfähigkeit des Dienstes). Da die Functional Software, Inc. ihren Sitz in den USA hat, kann ein Drittlandtransfer (insbesondere im Rahmen des Konzernverbunds bzw. bei Support- und Wartungsleistungen) nicht ausgeschlossen werden. Hinweise zu den hierfür getroffenen Garantien finden Sie in Abschnitt 15.',
    },
    appStores: {
      title: '13. Bezug der App über App-Stores',
      content:
        'Der Download und die Installation der App erfolgen über den Apple App Store (Apple Distribution International Ltd., Hollyhill Industrial Estate, Hollyhill, Cork, Irland) bzw. den Google Play Store (Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland). Diese Plattformen erheben im Rahmen des Downloads und der Installation eigenständig Daten (z.B. Apple-ID bzw. Google-Konto, Geräteinformationen, Download-Zeitpunkt, Zahlungsinformationen) in eigener datenschutzrechtlicher Verantwortung. Hierauf haben wir keinen Einfluss. Es gelten die Datenschutzbestimmungen des jeweiligen App-Store-Betreibers.',
    },
    internationalTransfers: {
      title: '14. Internationale Datenübermittlungen',
      content:
        'Im Rahmen der oben beschriebenen Verarbeitungen kann es zu Datenübermittlungen in Länder außerhalb des Europäischen Wirtschaftsraums (EWR) kommen, in denen kein dem europäischen Recht vergleichbares Datenschutzniveau besteht ("Drittländer"). Dies betrifft insbesondere folgende Dienste:',
      transfers: {
        cloudflare:
          'Cloudflare, Inc. (USA): Eingesetzt zur Abwehr von Spam und Missbrauch. Die Übermittlung erfolgt auf Grundlage der EU-Standardvertragsklauseln (Art. 46 Abs. 2 lit. c DSGVO) sowie - soweit anwendbar - auf Grundlage des EU-US Data Privacy Framework (Angemessenheitsbeschluss der EU-Kommission vom 10.07.2023, Art. 45 DSGVO).',
        sentry:
          'Functional Software, Inc. / Sentry (USA): Eingesetzt zur Fehlererkennung. Die Verarbeitung erfolgt primär in der EU-Region; etwaige Übermittlungen in die USA erfolgen auf Grundlage der EU-Standardvertragsklauseln und - soweit anwendbar - des EU-US Data Privacy Framework.',
        telegram:
          'Telegram FZ-LLC (Vereinigte Arabische Emirate): Eingesetzt zur Synchronisation von Meldungen mit der FreiFahren_BE-Gruppe. Für die VAE liegt kein Angemessenheitsbeschluss der EU-Kommission vor. Wir verarbeiten in diesem Kontext ausschließlich anonymisierte Meldedaten (Linie, Station, Richtung, Uhrzeit) ohne unmittelbare Personenbezugsdaten; zu einem möglichen indirekten Personenbezug durch Zeitstempelkorrelation siehe Abschnitt 5. Nutzern, die Meldungen direkt in der Telegram-Gruppe absetzen, empfehlen wir, die Datenschutzhinweise von Telegram zu beachten.',
        stripe:
          'Stripe Payments Europe, Ltd. (Irland) / Stripe, Inc. (USA): Eingesetzt zur Abwicklung freiwilliger Beiträge. Vertragspartner ist die in Irland ansässige Stripe Payments Europe, Ltd.; im Rahmen des Konzernverbunds kann es zu Übermittlungen an die US-Muttergesellschaft Stripe, Inc. kommen. Stripe verarbeitet Zahlungsdaten (z. B. Kartendaten) in eigener datenschutzrechtlicher Verantwortung. Für etwaige Übermittlungen in die USA erfolgt die Absicherung auf Grundlage der EU-Standardvertragsklauseln (Art. 46 Abs. 2 lit. c DSGVO) sowie - soweit anwendbar - des EU-US Data Privacy Framework (Stripe ist DPF-zertifiziert). Die Datenschutzhinweise von Stripe sind unter https://stripe.com/de/privacy abrufbar.',
      },
      rights:
        'Eine Kopie der jeweils einschlägigen Garantien (insbesondere der EU-Standardvertragsklauseln) können Sie bei uns unter contact@freifahren.org anfordern.',
    },
    dataProcessing: {
      title: '15. Auftragsverarbeitung',
      content:
        'Soweit externe Dienstleister im Rahmen der Datenverarbeitung eingesetzt werden, handelt es sich um Auftragsverarbeiter im Sinne des Art. 28 DSGVO. Mit Sentry (Functional Software, Inc.) und Cloudflare, Inc. bestehen entsprechende Auftragsverarbeitungsverträge (Data Processing Addenda). Cloudflare, Inc. wird dabei überwiegend als Auftragsverarbeiter tätig; für Maßnahmen der Angriffs- und Missbrauchsabwehr handelt Cloudflare als eigenständig Verantwortlicher. Mit Hetzner Online GmbH besteht ein Auftragsverarbeitungsvertrag. Mit Mistral AI SAS besteht ein Auftragsverarbeitungsvertrag (Data Processing Addendum), der als Bestandteil des Nutzungsvertrags gilt. Vertragspartner für die Zahlungsabwicklung ist die Stripe Payments Europe, Ltd.; die zwischen den Parteien geltende Data Processing Agreement ist Bestandteil des Stripe-Nutzungsvertrags. Soweit Stripe Zahlungsdaten zu eigenen Zwecken (insbesondere Betrugsprävention sowie zur Erfüllung regulatorischer Pflichten) verarbeitet, handelt Stripe insoweit als eigenständig Verantwortlicher.',
    },
  },
});
