FROM golang as backend

WORKDIR /project

COPY packages/backend/ /project
COPY .docker_env /project/.env

RUN go install

COPY packages/backend/api/prediction/requirements.txt /project/api/prediction/requirements.txt
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install -r /project/api/prediction/requirements.txt

EXPOSE 8080

CMD ["go", "run", "main.go"]
