/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: ebad21b0e0318f2f052d8cfcdd3e217f)
interface __BaseEnv_Env {
	NODE_ENV: "production";
	BACKEND_URL: "https://api.freifahren.org";
	MISTRAL_MODEL: "mistral-small-latest";
	SENTRY_DSN: "https://9d9ac700f1213d4db367b557167a0594@o4508609338867712.ingest.de.sentry.io/4511633367564368";
	REPORT_GATE: Service /* entrypoint TrustedTelegramReportsEntrypoint from report-gate */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "BACKEND_URL" | "MISTRAL_MODEL" | "SENTRY_DSN">> {}
}
