/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: 2dd2f67520df00414f836eb364d97c0d)
interface __BaseEnv_Env {
	NODE_ENV: "production";
	BACKEND_URL: "https://api.freifahren.org";
	MISTRAL_MODEL: "mistral-small-latest";
	SENTRY_DSN: "https://9d9ac700f1213d4db367b557167a0594@o4508609338867712.ingest.de.sentry.io/4511633367564368";
	CITY_DELIVERY: DurableObjectNamespace<import("./src/index").CityDelivery>;
	TRANSIT_API: Fetcher /* api-worker */;
	REPORT_API: Service /* entrypoint TrustedTelegramReportsEntrypoint from api-worker */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CityDelivery";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "BACKEND_URL" | "MISTRAL_MODEL" | "SENTRY_DSN">> {}
}
