name: freifahren-backend

services:
  api:
    build:
      context: .
      target: development
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${HOST_DB_URL}:${DB_URL}
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app/
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
  nginx:
    image: nginx:1.27.0
    restart: unless-stopped
    ports:
      - 8080:80
      - 8083:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/:/etc/nginx/sites-available
