services:
  api:
    env_file: .env
    build:
      context: .
      target: development
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app/
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
