services:
  tileserver:
    image: ghcr.io/maplibre/martin:1.8.2
    command: ["--config", "/config/config.yaml"]
    ports:
      - "3000:3000"
    volumes:
      - ../martin:/config:ro
      - ../fonts:/fonts:ro
      - ./data:/tiles:ro
      - ./styles:/styles:ro
    restart: unless-stopped
