/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as MapRouteImport } from './routes/_map'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as MapIndexRouteImport } from './routes/_map/index'
import { Route as ReportsStationsRouteImport } from './routes/reports/stations'
import { Route as ReportsLinesRouteImport } from './routes/reports/lines'
import { Route as MapSettingsIndexRouteImport } from './routes/_map/settings/index'
import { Route as MapStationStationIdRouteImport } from './routes/_map/station/$stationId'
import { Route as MapReportsStationIdRouteImport } from './routes/_map/reports/$stationId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/_map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const ReportsStationsRoute = ReportsStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsLinesRoute = ReportsLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => ReportsRoute,
} as any)
const MapSettingsIndexRoute = MapSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MapRoute,
} as any)
const MapStationStationIdRoute = MapStationStationIdRouteImport.update({
  id: '/station/$stationId',
  path: '/station/$stationId',
  getParentRoute: () => MapRoute,
} as any)
const MapReportsStationIdRoute = MapReportsStationIdRouteImport.update({
  id: '/reports/$stationId',
  path: '/reports/$stationId',
  getParentRoute: () => MapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MapIndexRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reports/lines': typeof ReportsLinesRoute
  '/reports/stations': typeof ReportsStationsRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/$stationId': typeof MapReportsStationIdRoute
  '/station/$stationId': typeof MapStationStationIdRoute
  '/settings/': typeof MapSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reports/lines': typeof ReportsLinesRoute
  '/reports/stations': typeof ReportsStationsRoute
  '/': typeof MapIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/$stationId': typeof MapReportsStationIdRoute
  '/station/$stationId': typeof MapStationStationIdRoute
  '/settings': typeof MapSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_map': typeof MapRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reports/lines': typeof ReportsLinesRoute
  '/reports/stations': typeof ReportsStationsRoute
  '/_map/': typeof MapIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/_map/reports/$stationId': typeof MapReportsStationIdRoute
  '/_map/station/$stationId': typeof MapStationStationIdRoute
  '/_map/settings/': typeof MapSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impressum'
    | '/privacy'
    | '/report'
    | '/reports'
    | '/reports/lines'
    | '/reports/stations'
    | '/reports/'
    | '/reports/$stationId'
    | '/station/$stationId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/impressum'
    | '/privacy'
    | '/report'
    | '/reports/lines'
    | '/reports/stations'
    | '/'
    | '/reports'
    | '/reports/$stationId'
    | '/station/$stationId'
    | '/settings'
  id:
    | '__root__'
    | '/_map'
    | '/impressum'
    | '/privacy'
    | '/report'
    | '/reports'
    | '/reports/lines'
    | '/reports/stations'
    | '/_map/'
    | '/reports/'
    | '/_map/reports/$stationId'
    | '/_map/station/$stationId'
    | '/_map/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapRoute: typeof MapRouteWithChildren
  ImpressumRoute: typeof ImpressumRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ReportsRoute: typeof ReportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map': {
      id: '/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/_map/': {
      id: '/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/reports/stations': {
      id: '/reports/stations'
      path: '/stations'
      fullPath: '/reports/stations'
      preLoaderRoute: typeof ReportsStationsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/lines': {
      id: '/reports/lines'
      path: '/lines'
      fullPath: '/reports/lines'
      preLoaderRoute: typeof ReportsLinesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/_map/settings/': {
      id: '/_map/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MapSettingsIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/station/$stationId': {
      id: '/_map/station/$stationId'
      path: '/station/$stationId'
      fullPath: '/station/$stationId'
      preLoaderRoute: typeof MapStationStationIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/reports/$stationId': {
      id: '/_map/reports/$stationId'
      path: '/reports/$stationId'
      fullPath: '/reports/$stationId'
      preLoaderRoute: typeof MapReportsStationIdRouteImport
      parentRoute: typeof MapRoute
    }
  }
}

interface MapRouteChildren {
  MapIndexRoute: typeof MapIndexRoute
  MapReportsStationIdRoute: typeof MapReportsStationIdRoute
  MapStationStationIdRoute: typeof MapStationStationIdRoute
  MapSettingsIndexRoute: typeof MapSettingsIndexRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapIndexRoute: MapIndexRoute,
  MapReportsStationIdRoute: MapReportsStationIdRoute,
  MapStationStationIdRoute: MapStationStationIdRoute,
  MapSettingsIndexRoute: MapSettingsIndexRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

interface ReportsRouteChildren {
  ReportsLinesRoute: typeof ReportsLinesRoute
  ReportsStationsRoute: typeof ReportsStationsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsLinesRoute: ReportsLinesRoute,
  ReportsStationsRoute: ReportsStationsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MapRoute: MapRouteWithChildren,
  ImpressumRoute: ImpressumRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ReportsRoute: ReportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
