/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationsStationIdRouteImport } from './routes/stations/$stationId'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/report' | '/stations/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/report' | '/stations/$stationId'
  id: '__root__' | '/' | '/report' | '/stations/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  StationsStationIdRoute: StationsStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
