services:
    postgres:
        image: postgres:18.0-alpine3.22
        container_name: hono-postgres
        environment:
            POSTGRES_DB: freifahren
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

    bun:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hono-bun
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/freifahren
        ports:
            - '80:3000'
        volumes:
            - ./src:/app/src:ro
            - ./drizzle.config.ts:/app/drizzle.config.ts:ro
            - ./drizzle:/app/drizzle
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

volumes:
    postgres_data:
