name: Deploy Go App (backend)

on:
    push:
        branches:
            - main
        paths:
            - 'packages/backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Go App
              run: |
                  cd ./packages/backend/ && go build
            - name: Copy Go App to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.IP_ADDRESS }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  source: packages/backend/backend
                  target: /root/FreiFahren/packages/backend
            - name: Restart Go Service
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.IP_ADDRESS }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      sudo systemctl restart freifahren-backend.service
