name: Python Bot Linting (bot)

on:
  pull_request:
    paths:
      - '**.py'
      - 'setup.cfg'
      - 'requirements.txt'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          cd packages/FreiFahren_BE-NLP/ && python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 linting
        run: cd packages/FreiFahren_BE-NLP/ && flake8 .
