name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: 'Create env file'
        run: |
          touch .env
          echo export DB_USER="${{ secrets.DB_USER }}"  >> .env
          echo export DB_HOST="${{ secrets.DB_HOST }}"  >> .env
          echo export DB_PORT="${{ secrets.DB_PORT }}"  >> .env
          echo export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"  >> .env
          echo export DB_NAME = "${{ secrets.DB_NAME }}"  >> .env  
          cat .env
          pwd
          ls

          
      - name: Build
        run: go build

      - name: Run tests
        run: go test ./...
