name: Run Go Tests (backend)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to $RUNNER_TEMP
          chmod +x $RUNNER_TEMP/just
      - name: 'Create env file'
        run: |
          cd packages/backend/ &&  touch .env
          echo "export DB_URL=/app/test.sqlite3" >> .env
          echo "export HOST_DB_URL=$RUNNER_TEMP/test.sqlite3" >> .env
          cat .env

      - name: Run tests
        run: $RUNNER_TEMP/just test
