name: Run Go Tests (backend)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to $RUNNER_TEMP
          chmod +x $RUNNER_TEMP/just
      - name: 'Create env file'
        run: |
          touch .env
          echo "CGO_ENABLED=1" >> .env.test
          echo "DB_URL=/app/test.sqlite3" >> .env.test
          echo "HOST_DB_URL=$(pwd)/test.sqlite3" >> .env.test

      - name: Run tests
        run: $RUNNER_TEMP/just test
